package com.example.kayakquest.operations

data class FloatPlan(
    var kayakerName: String = "",
    var gender: String = "",
    var phoneNumber: String = "",
    var age: Int = 0,
    var address: String = "",
    var city: String = "",
    var state: String = "",
    var emergencyContact: String = "",
    var emergencyPhone: String = "",
    var kayakMake: String = "",
    var kayakModel: String = "",
    var kayakLength: String = "",
    var kayakColor: String = "",
    var safetyEquipmentNotes: String = "",
    var vehicleMake: String = "",
    var vehicleColor: String = "",
    var vehicleModel: String = "",
    var plateNumber: String = "",
    var departureDate: String = "",
    var departureTime: String = "",
    var putInLocation: String = "",
    var takeOutLocation: String = "",
    var returnTime: String = "",
    var tripNotes: String = "",
    var userId: String = "",
    var pdfUrl: String? = null
) {
    fun toMap(): Map<String, Any?> = mapOf(
        "kayakerName" to kayakerName,
        "gender" to gender,
        "age" to age,
        "address" to address,
        "city" to city,
        "state" to state,
        "emergencyContact" to emergencyContact,
        "emergencyPhone" to emergencyPhone,
        "kayakMake" to kayakMake,
        "kayakModel" to kayakModel,
        "kayakLength" to kayakLength,
        "kayakColor" to kayakColor,
        "vehicleModel" to vehicleModel,
        "plateNumber" to plateNumber,
        "safetyEquipmentNotes" to safetyEquipmentNotes,
        "vehicleMake" to vehicleMake,
        "vehicleColor" to vehicleColor,
        "departureDate" to departureDate,
        "departureTime" to departureTime,
        "putInLocation" to putInLocation,
        "takeOutLocation" to takeOutLocation,
        "returnTime" to returnTime,
        "tripNotes" to tripNotes,
        "userId" to userId,
        "pdfUrl" to pdfUrl,
    )
}